---
services:
  authelia:
    container_name: 'authelia'
    depends_on:
      traefik:
        condition: service_healthy
    hostname: ${SERVICES_AUTHELIA_HOSTNAME:-authelia}
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    env_file:  ${ABSOLUTE_PATH}/data/authelia/.env
    networks:
      proxy:
        ipv4_address: ${SERVICES_AUTHELIA_NETWORKS_PROXY_IPV4:-172.31.191.200}
        ipv6_address: ${SERVICES_AUTHELIA_NETWORKS_PROXY_IPV6:-fd00:1:be:a:7001:0:3e:7f00}
      socket_proxy:
        ipv4_address: ${SERVICES_AUTHELIA_NETWORKS_SOCKET_PROXY_IPV4:-172.31.255.200}
        ipv6_address: ${SERVICES_AUTHELIA_NETWORKS_SOCKET_PROXY_IPV6:-fd00:1:be:a:7001:0:3e:8f00}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ABSOLUTE_PATH}/data/authelia/config:/config
    secrets: ['JWT_SECRET', 'SESSION_SECRET', 'STORAGE_ENCRYPTION_KEY'] # 'NOTIFIER_SMTP_PASSWORD'
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
      # AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: '/run/secrets/NOTIFIER_SMTP_PASSWORD
      
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: HOST(`auth.domain.tld`)
      traefik.http.routers.authelia.entryPoints: websecure
      traefik.http.routers.authelia.tls: true
      traefik.http.routers.authelia.tls.certresolver: tls_resolver
      traefik.http.services.authelia.loadbalancer.server.port: 9091
      traefik.http.middlewares.authelia.forwardAuth.address: https://authelia:9091/api/authz/forward-auth
      traefik.http.routers.authelia.middlewares: default@file
      traefik.http.routers.authelia.service: authelia
    security_opt:
      - no-new-privileges:true
secrets:
  JWT_SECRET:
    file: ${SECRETDIR}/authelia/authelia_jwt_secret
  SESSION_SECRET:
    file: ${SECRETDIR}/authelia/authelia_session_secret
  STORAGE_ENCRYPTION_KEY:
    file: ${SECRETDIR}/authelia/authelia_storage_encryption_key
  # NOTIFIER_SMTP_PASSWORD:
  #   file: ${SECRETDIR}/authelia/authelia_notifier_smtp_password

...